[build]
  publish = "dist/"
  command = "pnpm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"

[[redirects]]
  from = "/tera/*"
  to = "https://fluid-earth.byrd.osu.edu/tera/:splat"
  status = 200
  force = true
