[build]
  publish = "dist/"
  command = "npm run build:app"
  ignore = "[[ $HEAD == master ]]"

[build.environment]
  NODE_VERSION = "14"
  NPM_VERSION = "7"

[[redirects]]
  from = "/data/*"
  to = "https://fever.byrd.osu.edu/fev2r-data-3/:splat"
  status = 200
  force = true
